### ISSUE TITLE
It's not a bug, I just wanted to know how to use an Ubuntu image because everything I tried didn't work

### ISSUE THREAD

**Issue by daviDarthemis** [LekKit/RVVM#113]
Hello, I'm trying to use an Ubuntu image but it didn't work even in img. I don't know if I'm converting the file correctly, I wanted an explanation on how to use Ubuntu

**Comment by LekKit** [comment]
Here you can get a [working image](https://cdimage.ubuntu.com/releases/23.10/release/ubuntu-23.10-preinstalled-server-riscv64.img.xz) (Ubuntu Server image for QEMU or Unmatched should work), then unpack with `xz -d -T0 [filename]`

For booting the image you should also get a working OpenSBI+UBoot firmware (Basically a BIOS for this VM) which you can get [here](https://github.com/LekKit/patches-misc/releases/download/rvvm-uboot-2023.4/fw_payload.bin)

It is also important that Ubuntu is very RAM-hungry, the default VM setting of 256Mb doesn't work - so you should allocate at least 2G of RAM or so.
Here is a reference cmdline: `rvvm fw_payload.bin -i ubuntu-23.10-preinstalled-server-riscv64.img -m 2G -smp 4`

Sometimes the GRUB timeout is not working, this is seemingly a GRUB bug and you can press `Enter` over the serial console (VM terminal) to skip this.
First boot seems to be very slow, because the image automatically updates itself once.
Log in with ubuntu:ubuntu user, good luck)

![image](https://github.com/LekKit/RVVM/assets/50500857/0376cbb5-2b8f-46e7-8ffd-7b5df3186f41)

**Comment by LekKit** [comment]
Closing this one for now, reopen if any additional help is needed
