### ISSUE TITLE
[Haiku host] Freeze on shutdown

### ISSUE THREAD

**Issue by X547** [LekKit/RVVM#127]
RVVM freeze when shutting down guest with window close button or request from guest OS.

![screenshot619](https://github.com/LekKit/RVVM/assets/45505339/9f4ff354-e4b5-454c-9bcf-7ed273dcde88)
Host OS: Haiku x86_64.

**Comment by LekKit** [comment]
> RVVM freeze when shutting down guest with window close button or request from guest OS.

Can you give a backtrace of TAP thread? Apparently it's locking up somewhere so `thread_join()` is waiting endlessly inside `tap_close()` inlined into `rtl8169_remove()`

It might as well be related to the `select()` Haiku bug we spoke a while ago where it doesn't report closed connections. I am currently using a socket pair to signal the TAP thread that it should shut down by closing one end of it.

Will get a repro soon on a fresh Haiku x86_64 install.

**Comment by LekKit** [comment]
That's exactly what I thought: `tap_thread` stuck inside `_kern_select` even tho a sockpair side is closed; Main thread endlessly waits inside `thread_join()`

See https://dev.haiku-os.org/ticket/18327. Apparently it regressed again? I am on a freshly installed `hrev57617`.

![image](https://github.com/LekKit/RVVM/assets/50500857/d19c76ce-f8ed-4427-a6a2-a7bdd09e28f4)

![image](https://github.com/LekKit/RVVM/assets/50500857/8bd31819-9200-4f21-b87b-35b8f4fded26)

I can attempt a workaround for this hang in RVVM code, like writing to the socketpair so the paired socket wakes up `select()` due to data being available (If that works).

However this issue not only affects thread shutdown but also all TCP connections - the guest will never get a FIN/RST for a closed connection; TCP connection state will not be freed until guest sends a RST or keepalive timer expires. In other words this kernel bug (apparently) causes the entire RVVM networking stack to misbehave.

**Comment by LekKit** [comment]
Downgrading to `hrev57013` fixes the issue.

```
# pkgman add https://eu.hpkg.haiku-os.org/haiku/master/x86_64/r1~beta4_hrev57013
# pkgman full-sync
```

![image](https://github.com/LekKit/RVVM/assets/50500857/922b8c64-9613-4bd9-849b-eaab8a2bc5e3)

**Comment by LekKit** [comment]
Bisect progress:

`hrev57215`: Doesn't boot beyond splash with all icons colored - skip
`hrev57114`: No issue
`hrev57414`: No issue
`hrev57517`: No issue
`hrev57588`: Test `haiku_select_repro.c` hangs, RVVM hangs on exit; Network operations with `pkgman` stutter significantly.
`hrev57560`: Test `haiku_select_repro.c` hangs, RVVM hangs on exit; Network operations with `pkgman` stutter significantly. Upon first attempt `pkgman full-sync` errored out with "*** Failed to download package haiku: Operation would block"
`hrev57530`: No issue
`hrev57545`: No issue
`hrev57554`: Test `haiku_select_repro.c` hangs, ...

Apparently the issue was reintroduced after `hrev57545`, up to `hrev57554`. No other available binary revisions in the repo.

Reopened related Haiku ticket: https://dev.haiku-os.org/ticket/18327

**Comment by LekKit** [comment]
Should be fixed by Haiku `hrev57626`
https://git.haiku-os.org/haiku/commit/src/add-ons/kernel/network/protocols/tcp?id=49d736ca2a618c5cc9f10d833c7aa7f080451ab9

**Comment by LekKit** [comment]
The fix has reached binary repos as `hrev57627`. Anyone who downgraded can revert version pinning with:
```
pkgman add https://eu.hpkg.haiku-os.org/haiku/master/x86_64/current
pkgman full-sync
```
