### ISSUE TITLE
rmmv -i img kernel support

### ISSUE THREAD

**Issue by ZLangJIT** [LekKit/RVVM#142]
in order to reduce memory consumption for a booted kernel initramfs filesystem, i intend to utilize rvvm's disk image loading capabilities to mount host filesystem disk images ( eg `-i ~/storage.img` ) since we almost always have signifigantly more hdd/sdd storage than we have available RAM (and especially in environments where RAM should be very minimal)

what would i need to enable in a custom kernel in order to support picking up and mounting images passed via `rvvm -i` command, specifically in a buildroot initramfs (busybox shell)

specifically i intend to use this to be able to transfer data to/from guest/host and set up complex filesystems in host then expose to guest (eg, to pass multiple directories/files from guest to host or from host to guest, which the guest can then mount and do whatever with

in addition to possible additional fuse overlay packages  (eg   -i pkg1 -i pkg2 ect)

additionally how would we create/prepare such an image for passing to `rvvm -i` and mounting via `mount ...`

and if possible, how may we support the TRIM nvme option that rvvm supports

**Comment by LekKit** [comment]
RVVM `-i` argument attaches a PCIe NVMe device, with the passed file as a raw disk image. More image formats are going to be implemented (QCOW via libqcow, and an in-house deduplication format).
You need PCIe NVMe driver enabled in the guest kernel in order to detect the device.

TRIM support is usually transparent, but needs a host OS & FS that support sparse files and hole punching (Linux, Windows with NTFS, FreeBSD).

Raw image files have the advantage of being able to interact with the host too. Depending on whether the image cointains the FS directly, or has a partition table, trying `# mount storage.img /mnt` or `losetup -P /dev/loop0 storage.img` can mount the guest filesystem on the host, or manifest guest partitions as `/dev/loop0p1`etc.

Be careful not to mount the same filesystem both inside the guest and on the host (corruptions may occur because they don't know about each other).

You may also use network mounts (sshfs, etc) if SSH is set up correctly in the guest. Address `localhost:2022` is routed into guest port 22, `-portfwd` argument may be used for additional port forwarding.
