### ISSUE TITLE
Remove RISC-V foundation official branding

### ISSUE THREAD

**Issue by dist1ll** [LekKit/RVVM#77]
Unless you're a special member of the the RISC-V foundation, you're not allowed to use the organization's trademark to advertise your projects (which includes logo and branding).

Just giving you a heads-up in case you were not aware.

**Comment by LekKit** [comment]
I had the suspicion of stuff like this since it's addition to the README, hence why I read the guidelines here: https://riscv.org/about/risc-v-branding-guidelines/.
I was under the impression that it is allowed for non-commercial purposes, especially since it is actually attributed as a RV International trademark, somewhere along those lines:
```
The RISC-V trade mark or the RISC-V logo may be freely used for non-commercial research
and academic projects as long as the guidelines below are followed. Individual members
may not use the RISC-V trademark for commercial purposes
```

I will consider removing it, but then it seems that either I didn't understand the actual agreement, or it's unclear under what terms the logo may actually be used (Esp. considering, is RVVM an actual core implementation? Does it fall into RV-compliant cores category?). Would be glad if you could clear some confusion on that. 

I already have a somewhat-authentic RVVM logo that is used in the build system and as EFI splash screen, inspired by certain 90s black metal bands, but if someone has an idea for a better one, I'd like to see that.


![image](https://user-images.githubusercontent.com/50500857/222776134-8417930a-49f9-4f67-9010-e5461fb655fd.png)

**Comment by dist1ll** [comment]
My bad, I misread the guidelines. Looks like it really does only apply for commercial projects.
